# Site settings
title: It's calling me again
email: zxteloiv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  僕は僕のことが知りたい...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liselsia.org" # the base hostname & protocol for your site
twitter_username: shion_shiina
github_username:  zxteloiv

# Build settings
markdown: kramdown
